const test = require( 'node:test' );
const assert = require( 'node:assert/strict' );
const scanner = require( '../../assets/js/pgr-structured-scanner-core.js' );

const sayadOutputs = [ 'qr_version', 'owner_type', 'owner_identifier', 'iban', 'bank_branch', 'cheque_serial', 'sayad_id' ];
const sayadProfile = { id: 'sayad_v01', parser: { type: 'segments_v1', separator: 'newline', trim: true, normalize_digits: true }, outputs: sayadOutputs.map( ( key ) => ( { key, required: true } ) ) };
const customProfile = { id: 'customer_card_v1', parser: { type: 'segments_v1', separator: 'newline', trim: true, normalize_digits: true }, outputs: [ { key: 'customer_id', required: true }, { key: 'reference_code', required: true }, { key: 'note', required: false } ] };
function resetProfiles( extra = [] ) { return scanner.configureProfiles( [ sayadProfile, ...extra ] ); }
function payload( values, separator = '\n' ) { return values.join( separator ); }
function validSayadValues( suffix = '' ) { return [ '01' + suffix, '1' + suffix, '0000000000' + suffix, 'IR000000000000000000000000' + suffix, '00-000' + suffix, '000000' + suffix, '0000000000000000' + suffix ]; }
function descriptors( outputs = sayadOutputs ) { return outputs.map( ( output, index ) => ( { id: String( 10 + index ), type: index % 2 === 0 ? 'text' : 'hidden', displayOnly: false } ) ); }
function mappings( outputs = sayadOutputs ) { const result = {}; outputs.forEach( ( output, index ) => { result[ output ] = String( 10 + index ); } ); return result; }
function applyForTest( state, plan ) { if ( ! plan.ok ) { return state; } const next = { ...state }; plan.updates.forEach( ( update ) => { next[ update.targetId ] = update.value; } ); return next; }
test.beforeEach( () => { resetProfiles(); } );

test( 'built-in Sayad keeps exact ordered output semantics', () => { const result = scanner.parseScan( payload( validSayadValues() ), 'sayad_v01' ); assert.equal( result.ok, true ); assert.deepEqual( result.outputs, sayadOutputs ); assert.equal( result.data.qr_version, '01' ); assert.equal( result.data.owner_identifier, '0000000000' ); assert.equal( result.data.sayad_id, '0000000000000000' ); } );
test( 'Sayad CRLF, trimming, Persian digits and leading zeroes remain compatible', () => { const values = validSayadValues(); values[2] = '  ۰۰۰۱۲۳۴۵۶۷  '; values[6] = '۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۱'; const result = scanner.parseScan( '\r\n' + payload( values, '\r\n' ) + '\r\n', 'sayad_v01' ); assert.equal( result.ok, true ); assert.equal( result.data.owner_identifier, '0001234567' ); assert.equal( result.data.sayad_id, '0000000000000001' ); } );
test( 'Sayad invalid segment count and empty required segment keep deterministic failures', () => { const short = scanner.parseScan( payload( validSayadValues().slice( 0, 6 ) ), 'sayad_v01' ); assert.deepEqual( short, { ok: false, code: 'INVALID_SEGMENT_COUNT', expected: 7, received: 6 } ); const values = validSayadValues(); values[3] = '   '; const empty = scanner.parseScan( payload( values ), 'sayad_v01' ); assert.equal( empty.code, 'EMPTY_SEGMENT' ); assert.equal( empty.segment, 4 ); } );
test( 'valid custom segments_v1 profile parses ordered outputs', () => { resetProfiles( [ customProfile ] ); const result = scanner.parseScan( '۰۰۱\nREF-9\nیادداشت', 'customer_card_v1' ); assert.equal( result.ok, true ); assert.deepEqual( result.outputs, [ 'customer_id', 'reference_code', 'note' ] ); assert.deepEqual( result.data, { customer_id: '001', reference_code: 'REF-9', note: 'یادداشت' } ); } );
test( 'optional trailing custom output is deterministic and may be empty', () => { resetProfiles( [ customProfile ] ); const result = scanner.parseScan( '42\nABC\n', 'customer_card_v1' ); assert.equal( result.ok, true ); assert.equal( result.data.note, '' ); } );
test( 'required custom output may not be empty', () => { resetProfiles( [ customProfile ] ); const result = scanner.parseScan( '42\n   \noptional', 'customer_card_v1' ); assert.equal( result.ok, false ); assert.equal( result.code, 'EMPTY_SEGMENT' ); assert.equal( result.segment, 2 ); } );
test( 'custom profile can disable trimming and digit normalization explicitly', () => { const literal = { id: 'literal_v1', parser: { type: 'segments_v1', separator: 'newline', trim: false, normalize_digits: false }, outputs: [ { key: 'literal', required: true } ] }; resetProfiles( [ literal ] ); const result = scanner.parseScan( '  ۱۲  ', 'literal_v1' ); assert.equal( result.ok, true ); assert.equal( result.data.literal, '  ۱۲  ' ); } );
test( 'malformed runtime profiles are rejected and never become executable', () => { const malformed = { id: 'bad_v1', parser: { type: 'regex', separator: 'newline', trim: true, normalize_digits: true }, outputs: [ { key: 'value', required: true } ] }; const configured = scanner.configureProfiles( [ sayadProfile, malformed ] ); assert.equal( configured.count, 1 ); assert.deepEqual( configured.rejected, [ 1 ] ); assert.deepEqual( scanner.parseScan( 'anything', 'bad_v1' ), { ok: false, code: 'PROFILE_NOT_FOUND' } ); } );
test( 'duplicate keys and executable-like parser models fail closed', () => { const duplicate = { ...customProfile, id: 'duplicate_v1', outputs: [ { key: 'same', required: true }, { key: 'same', required: false } ] }; const configured = scanner.configureProfiles( [ duplicate ] ); assert.equal( configured.count, 0 ); assert.deepEqual( scanner.parseScan( 'a\nb', 'duplicate_v1' ), { ok: false, code: 'PROFILE_NOT_FOUND' } ); } );
test( 'unavailable profile fails closed without parsing', () => { assert.deepEqual( scanner.parseScan( '1\n2\n3', 'customer_card_v1' ), { ok: false, code: 'PROFILE_NOT_FOUND' } ); } );
test( 'custom profile mapping validates and builds one atomic update plan', () => { resetProfiles( [ customProfile ] ); const parsed = scanner.parseScan( '42\nABC\nnote', 'customer_card_v1' ); const outputs = [ 'customer_id', 'reference_code', 'note' ]; const plan = scanner.buildUpdatePlan( parsed, mappings( outputs ), descriptors( outputs ), '99' ); assert.equal( plan.ok, true ); assert.deepEqual( plan.updates, [ { output: 'customer_id', targetId: '10', value: '42' }, { output: 'reference_code', targetId: '11', value: 'ABC' }, { output: 'note', targetId: '12', value: 'note' } ] ); } );
test( 'mapping with unknown custom output key fails closed', () => { resetProfiles( [ customProfile ] ); const parsed = scanner.parseScan( '42\nABC\nnote', 'customer_card_v1' ); const outputs = [ 'customer_id', 'reference_code', 'note' ]; const map = mappings( outputs ); map.renamed_output = '15'; const plan = scanner.buildUpdatePlan( parsed, map, descriptors( outputs ), '99' ); assert.equal( plan.ok, false ); assert.equal( plan.code, 'INVALID_MAPPING' ); assert.equal( Object.prototype.hasOwnProperty.call( plan, 'updates' ), false ); } );
test( 'duplicate destination, self target, missing target and unsupported type fail before updates', () => { const parsed = scanner.parseScan( payload( validSayadValues() ), 'sayad_v01' ); const duplicate = mappings(); duplicate.sayad_id = duplicate.iban; assert.equal( scanner.buildUpdatePlan( parsed, duplicate, descriptors(), '99' ).code, 'DUPLICATE_TARGET' ); const self = mappings(); self.qr_version = '99'; assert.equal( scanner.buildUpdatePlan( parsed, self, descriptors().concat( { id: '99', type: 'text', displayOnly: false } ), '99' ).code, 'SELF_TARGET' ); assert.equal( scanner.buildUpdatePlan( parsed, mappings(), descriptors().slice( 0, 6 ), '99' ).code, 'TARGET_NOT_FOUND' ); const targets = descriptors(); targets[3] = { id: '13', type: 'number', displayOnly: false }; assert.equal( scanner.buildUpdatePlan( parsed, mappings(), targets, '99' ).code, 'UNSUPPORTED_TARGET' ); } );
test( 'failed second scan cannot alter state produced by first successful scan', () => { const first = scanner.parseScan( payload( validSayadValues() ), 'sayad_v01' ); const firstPlan = scanner.buildUpdatePlan( first, mappings(), descriptors(), '99' ); const afterFirst = applyForTest( {}, firstPlan ); const invalidSecond = scanner.parseScan( payload( validSayadValues().slice( 0, 6 ) ), 'sayad_v01' ); const failedPlan = scanner.buildUpdatePlan( invalidSecond, mappings(), descriptors(), '99' ); assert.equal( failedPlan.ok, false ); assert.deepEqual( applyForTest( afterFirst, failedPlan ), afterFirst ); } );
test( 'capture completion stays parser driven for Enter idle Tab and paste', () => { for ( let count = 1; count <= 6; count++ ) { assert.equal( scanner.decideCaptureAction( payload( validSayadValues().slice( 0, count ) ), 'sayad_v01', 'enter' ).action, 'continue' ); } const complete = payload( validSayadValues() ); assert.equal( scanner.decideCaptureAction( complete, 'sayad_v01', 'enter' ).action, 'finalize' ); assert.equal( scanner.decideCaptureAction( complete, 'sayad_v01', 'idle' ).action, 'finalize' ); assert.equal( scanner.decideCaptureAction( '1\n2', 'sayad_v01', 'tab' ).action, 'finalize' ); assert.equal( scanner.decideCaptureAction( '1\n2', 'sayad_v01', 'paste' ).action, 'finalize' ); } );
